"""add_route_and_spot_display_fields

Revision ID: 9e5c9bf7d5c7
Revises: dda5554fb7ff
Create Date: 2026-06-19 11:07:21.208595
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5c9bf7d5c7'
down_revision: Union[str, None] = 'dda5554fb7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenic_spots', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('scenic_spots', sa.Column('qa_json', sa.JSON(), nullable=True))
    op.add_column('scenic_spots', sa.Column('display_x', sa.Float(), nullable=True))
    op.add_column('scenic_spots', sa.Column('display_y', sa.Float(), nullable=True))
    op.add_column('tour_routes', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('tour_routes', sa.Column('brush_image', sa.String(length=255), nullable=True))
    op.add_column('tour_routes', sa.Column('opening_text', sa.Text(), nullable=True))
    op.add_column('tour_routes', sa.Column('closing_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_routes', 'closing_text')
    op.drop_column('tour_routes', 'opening_text')
    op.drop_column('tour_routes', 'brush_image')
    op.drop_column('tour_routes', 'color')
    op.drop_column('scenic_spots', 'display_y')
    op.drop_column('scenic_spots', 'display_x')
    op.drop_column('scenic_spots', 'qa_json')
    op.drop_column('scenic_spots', 'duration')
    # ### end Alembic commands ###
