"""add_spot_images_and_story_acts_and_route_cover

Revision ID: dda5554fb7ff
Revises: 001
Create Date: 2026-06-19 11:03:48.731321
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda5554fb7ff'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenic_spots', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    op.add_column('scenic_spots', sa.Column('detail_images', sa.JSON(), nullable=True))
    op.add_column('scenic_spots', sa.Column('story_acts', sa.JSON(), nullable=True))
    op.add_column('tour_routes', sa.Column('cover_image', sa.String(length=255), nullable=True))
    op.add_column('tourist_profiles', sa.Column('dna_type', sa.String(length=50), nullable=True))
    op.add_column('tourist_profiles', sa.Column('dna_scores', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_tourist_profiles_dna_type'), 'tourist_profiles', ['dna_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tourist_profiles_dna_type'), table_name='tourist_profiles')
    op.drop_column('tourist_profiles', 'dna_scores')
    op.drop_column('tourist_profiles', 'dna_type')
    op.drop_column('tour_routes', 'cover_image')
    op.drop_column('scenic_spots', 'story_acts')
    op.drop_column('scenic_spots', 'detail_images')
    op.drop_column('scenic_spots', 'thumbnail')
    # ### end Alembic commands ###
